### ISSUE TITLE
Possibly bug with large star

### ISSUE THREAD

**Issue by Camawama** [Povstalec/StellarView#4]
![image](https://github.com/Povstalec/StellarView/assets/43620900/eadb6f91-21e1-4c5f-bd36-2962938b0d0a)

The star was slightly larger a couple times but now it is HUGE!

**Comment by Camawama** [comment]
I don't know if it is supposed to be this huge!
![image](https://github.com/Povstalec/StellarView/assets/43620900/d131b95d-926e-47a8-9839-b8949deedaa5)

**Comment by Povstalec** [comment]
This is actually the new Supernova event that lasts for about 2 days. During a supernova explosion, one star expands over time until it almost starts to look like a "second sun" in the sky and then shrinks down until it disappears completely. I'll add more customization to it in the future, so that you can control approximately when it will appear or disable the event completely.

**Comment by Camawama** [comment]
Oh that's awesome!! Apologies for the false report 😅
